apiVersion: v1
kind: Secret
metadata:
  name: product-db-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=  # base64 encoded 'password'
