version: '3.8'

networks:
  internal:
    driver: bridge
  shared-network:
    external: true
    name: dairy-network

services:
  user-service-db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: userdb
      POSTGRES_PASSWORD: userservicepwd
      POSTGRES_USER: admin_user
    ports:
      - '5033:5432'
    volumes:
      - C:\Users\ymt01\Documents\db_volumes\user-service-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-service:latest
    container_name: user-service
    depends_on:
      user-service-db:
        condition: service_healthy
    ports:
      - '4001:4001'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://user-service-db:5432/userdb'
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: userservicepwd
      PRODUCT_SERVICE_URL: 'http://product-service:4000/api'
    networks:
      - internal
      - shared-network